-- Database Synchronization with ER Diagram
-- Created: 2026-02-19

-- 1. Chat History Table (For AI Context)
CREATE TABLE IF NOT EXISTS chat_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES profiles(id) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'system')),
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Processed Events Table (For Webhook Deduplication)
CREATE TABLE IF NOT EXISTS processed_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id TEXT UNIQUE NOT NULL,
    line_user_id TEXT, -- Added for traceability
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Ensure Columns in Profiles (Idempotent checks)
-- Tier is already an ENUM 'user_tier', just ensuring column exists
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'tier') THEN
        ALTER TABLE profiles ADD COLUMN tier user_tier DEFAULT 'free';
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'tutorial_step') THEN
        ALTER TABLE profiles ADD COLUMN tutorial_step INTEGER DEFAULT 0;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'profiles' AND column_name = 'google_calendar_last_sync') THEN
        ALTER TABLE profiles ADD COLUMN google_calendar_last_sync TIMESTAMP WITH TIME ZONE;
    END IF;
END $$;

-- 4. RLS Policies

-- Chat History RLS
ALTER TABLE chat_history ENABLE ROW LEVEL SECURITY;

DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'chat_history' AND policyname = 'Users can view own chat history') THEN
        CREATE POLICY "Users can view own chat history" ON chat_history FOR SELECT USING (auth.uid() = user_id);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'chat_history' AND policyname = 'Users can insert own chat message') THEN
        CREATE POLICY "Users can insert own chat message" ON chat_history FOR INSERT WITH CHECK (auth.uid() = user_id);
    END IF;
END $$;

-- Processed Events RLS (Service Role mostly, but secure it)
ALTER TABLE processed_events ENABLE ROW LEVEL SECURITY;
-- No public policies needed as this is strictly backend/webhook managed
